package task3;

import java.util.*;

public enum Ctrpstn {

    expr1(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))),
    expr2(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))),
    expr3(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))),
    expr4(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))),
    expr5(new Then(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))))),
    expr6(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))))),
    expr7(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))))),
    expr8(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))))),
    expr9(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))),
    expr10(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))))),
    expr11(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))), new Then(new NumExpr(1), new NumExpr(2))))),
    expr12(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2)))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))), new Then(new NumExpr(1), new NumExpr(2)))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2)))))),
    expr13(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))), new Then(new NumExpr(1), new NumExpr(2)))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))))),
    expr14(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2)))),
    expr15(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))))),
    expr16(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2)))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))))))),
    expr17(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2)))))),
    expr18(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))))))),
    expr19(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2)))))),
    expr20(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))))),
    expr21(new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))),
    expr22(new Then(new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))))),
    expr23(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))))),
    expr24(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2)))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))))),
    expr25(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))))),
    expr26(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))),
    expr27(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))))),
    expr28(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))))),
    expr29(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))))),
    expr30(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))),
    expr31(new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))),
    expr32(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))))),
    expr33(new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))),
    expr34(new Then(new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))))),
    expr35(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))))))),
    expr36(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))))),
    expr37(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))))))),
    expr38(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))),
    expr39(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))))),
    expr40(new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))))))),
    expr41(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))))),
    expr42(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2))))),
    expr43(new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2))))))),
    expr44(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))))),
    expr45(new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))))),
    expr46(new Then(new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))))))),
    expr47(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))))))),
    expr48(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))))))),
    expr49(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))))))),
    expr50(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))))),
    expr51(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2))))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))))))),
    expr52(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Not(new NumExpr(2)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))))),
    expr53(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))))),
    expr54(new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))),
    expr55(new Then(new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))))),
    expr56(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))))))),
    expr57(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2)))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))))),
    expr58(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Not(new NumExpr(2))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))))))),
    expr59(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))),
    expr60(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))),
    expr61(new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))))),
    expr62(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))))),
    expr63(new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))),
    expr64(new Then(new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))))),
    expr65(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1))))))),
    expr66(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))))),
    expr67(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1))))))),
    expr68(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))),
    expr69(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2))))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))))),
    expr70(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new NumExpr(1), new Not(new NumExpr(2)))), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1))))))),
    expr71(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))),
    expr72(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1))))), new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1))))))),
    expr73(new Then(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Then(new Not(new NumExpr(2)), new Then(new Then(new NumExpr(1), new Not(new NumExpr(2))), new Not(new NumExpr(1)))), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1))))), new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))))),
    expr74(new Then(new Then(new NumExpr(1), new NumExpr(2)), new Then(new Not(new NumExpr(2)), new Not(new NumExpr(1)))));
    private final Expression expression;

    Ctrpstn(Expression expression) {
        this.expression = expression;
    }

    public Expression getExpression() {
        return expression;
    }

    public Expression replace(Expression e, Expression e1) {
        Map<String, Expression> map = new HashMap<>();
        map.put("1", e);
        map.put("2", e1);
        return expression.subAndCopy(map);
    }

    public String replace(String e, String e1) {
        return replace(Helper.parse(e), Helper.parse(e1)).toString();
    }
}
